# Generated by Django 4.2.5 on 2023-09-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='value',
            field=models.FileField(upload_to='alldocuments'),
        ),
    ]
