# Generated by Django 4.2.5 on 2023-09-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_documents_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='value',
            field=models.ImageField(upload_to='alldocuments'),
        ),
    ]
