# Generated by Django 4.2.5 on 2023-09-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_documents_date_remove_documents_room_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
