# Generated by Django 4.2.5 on 2023-09-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='islawyer',
            field=models.BooleanField(default=False),
        ),
    ]
