# Generated by Django 4.2.5 on 2023-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_advocate_islawyer_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='advocate_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='practice_area',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='advocate_pics'),
        ),
        migrations.AddField(
            model_name='advocate',
            name='ratingno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
