# Generated by Django 4.2.5 on 2023-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advocate_advocate_id_advocate_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='practice_area',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
