# Generated by Django 4.2.5 on 2023-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_advocate_user_alter_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='practice_area',
            new_name='practice_areas',
        ),
        migrations.AlterField(
            model_name='advocate',
            name='ratingno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='ratings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
