# Generated by Django 4.2.5 on 2023-09-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_practice_area_advocate_practice_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
