# Generated by Django 4.2.5 on 2023-09-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_advocate_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='case_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='isadvocate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='isarbitrator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='isdocument_writer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='islawyer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='ismediator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='isnotaries',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
