# Generated by Django 4.2.5 on 2023-09-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_advocate_bio_advocate_case_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='islawyer',
            field=models.BooleanField(default=False),
        ),
    ]
