# Generated by Django 4.2.5 on 2023-09-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_advocate_islawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='advocate_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='case_summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
