# Generated by Django 4.2.5 on 2023-09-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_advocate_advocate_id_alter_advocate_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='islawyer',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
